name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Publish Windows x64 package
        run: dotnet publish SnapDescribe.App -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true

      - name: Package artifacts
        run: |
          cd SnapDescribe.App/bin/Release/net8.0/win-x64/publish
          zip -r SnapDescribe-win-x64.zip *
          mv SnapDescribe-win-x64.zip ../../../../../../

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: SnapDescribe-win-x64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
